apiVersion: v1
kind: Service
metadata:
  name: skhappycampus-analysis-service
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    nodePort: 30082
  selector:
    run: skhappycampus-analysis
  type: NodePort
